version: '3'

services:
  redis:
    image: redis:7.0.2
    ports:
      - 6379:6379
    command: redis-server --save 60 1 --requirepass redispw --loglevel warning

  oracle:
    image: gvenzl/oracle-xe:21.3.0
    ports:
      - 1521:1521
    environment:
      ORACLE_PASSWORD: myPassword
